---
title: "Tarea Optativa A."
author: "Gabriela Michelle Alvarez Guerra"
lang: es
format: 
  html:
    grid:
      body-width: 1200px
---


```{python}
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve, minimize
```

Utilizar las funciones `fsolve` y `minimize` de `scipy.optimize` para obtener soluciones aproximadas.

## Ejercicio 1

Aproxima la solución de los siguientes sistemas no lineales. Para cada inciso, grafica las curvas implícitas $f_1(x_1,x_2)=0$ y $f_2(x_1,x_2)=0$, indicando las soluciones encontradas.

**(a)**

\begin{eqnarray}
4x_1^2 - 20x_1 + \frac{1}{4}x_2^2 + 8 &=& 0, \\
\frac{1}{2}x_1 x_2^2 + 2x_1 - 5x_2 + 8 &=& 0.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]

    f1 = 4*x1**2 - 20*x1 + (1/4)*x2**2 + 8
    f2 = (1/2)*x1*x2**2 + 2*x1 - 5*x2 + 8

    return [f1, f2]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [1, 1])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2

sol_min = minimize(objetivo, [1, 1])
print("Solución con minimize:", sol_min.x)
```

**Gráfica inciso (a)**

```{python}
x1 = np.linspace(-1, 6, 600)
x2 = np.linspace(-10, 10, 600)

X1, X2 = np.meshgrid(x1, x2)

F1 = 4*X1**2 - 20*X1 + (1/4)*X2**2 + 8
F2 = (1/2)*X1*X2**2 + 2*X1 - 5*X2 + 8

plt.figure(figsize=(8,6))

plt.contour(X1, X2, F1, levels=[0], colors='blue')
plt.contour(X1, X2, F2, levels=[0], colors='green')

plt.plot(sol_fsolve[0], sol_fsolve[1], 'ko', label='Solución')

plt.title('Inciso a)')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend()
plt.grid()
plt.show()
```

**(b)**

\begin{eqnarray}
3x_1^2 - x_2^2 &=& 0, \\
3x_1 x_2^2 - x_1^3 - 1 &=& 0.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]

    f1 = 3*x1**2 - x2**2
    f2 = 3*x1*x2**2-x1**3-1

    return [f1, f2]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [1, 1])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2

sol_min = minimize(objetivo, [1, 1])
print("Solución con minimize:", sol_min.x)
```

**Gráfica inciso (b)**

```{python}
x1 = np.linspace(-2, 2, 600)
x2 = np.linspace(-3, 3, 600)

X1, X2 = np.meshgrid(x1, x2)

F1 = 3*X1**2 - X2**2
F2 = 3*X1*X2**2 - X1**3 - 1

plt.figure(figsize=(8,6))

plt.contour(X1, X2, F1, levels=[0], colors='blue')
plt.contour(X1, X2, F2, levels=[0], colors='green')

plt.plot(sol_fsolve[0], sol_fsolve[1], 'ko', label='Solución')

plt.title('Inciso b)')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend()
plt.grid()
plt.show()
```


**(c)**

\begin{eqnarray}
\log(x_1^2 + x_2^2) - \sin(x_1 x_2) &=& \log 2 + \log \pi, \\
e^{x_1 - x_2} + \cos(x_1 x_2) &=& 0.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]

    f1 = np.log(x1**2 + x2**2) - np.sin(x1*x2) - np.log(2) - np.log(np.pi)
    f2 = np.exp(x1 - x2) + np.cos(x1*x2)

    return [f1, f2]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [2, 2])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2

sol_min = minimize(objetivo, [2, 2])
print("Solución con minimize:", sol_min.x)
```

**Gráfica inciso (c)**

```{python}
x1 = np.linspace(-3, 5, 600)
x2 = np.linspace(-1, 6, 600)

X1, X2 = np.meshgrid(x1, x2)

F1 = np.log(X1**2 + X2**2) - np.sin(X1*X2) - np.log(2) - np.log(np.pi)
F2 = np.exp(X1 - X2) + np.cos(X1*X2)

plt.figure(figsize=(8,6))

plt.contour(X1, X2, F1, levels=[0], colors='blue')
plt.contour(X1, X2, F2, levels=[0], colors='green')

plt.plot(sol_fsolve[0], sol_fsolve[1], 'ko', label='Solución')

plt.title('Inciso b)')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend()
plt.grid()
plt.show()
```

**(d)**

\begin{eqnarray}
\sin(4\pi x_1 x_2) - 2x_2 - x_1 &=& 0, \\
\left(\frac{4\pi - 1}{4\pi}\right)(e^{2x_1} - e) + 4ex_2^2 - 2ex_1 &=& 0.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]

    f1 = np.sin(4*np.pi*x1*x2) - 2*x2 - x1
    f2 = ((4*np.pi - 1)/(4*np.pi))*(np.exp(2*x1) - np.e) + 4*np.e*x2**2 - 2*np.e*x1

    return [f1, f2]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [0, 0])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2

sol_min = minimize(objetivo, [0, 0])
print("Solución con minimize:", sol_min.x)
```

**Gráfica inciso (d)**

```{python}
x1 = np.linspace(-1, 1.5, 600)
x2 = np.linspace(-1, 1, 600)

X1, X2 = np.meshgrid(x1, x2)

F1 = np.sin(4*np.pi*X1*X2) - 2*X2 - X1
F2 = ((4*np.pi - 1)/(4*np.pi))*(np.exp(2*X1) - np.e) + 4*np.e*X2**2 - 2*np.e*X1

plt.figure(figsize=(8,6))

plt.contour(X1, X2, F1, levels=[0], colors='blue')
plt.contour(X1, X2, F2, levels=[0], colors='green')

plt.plot(sol_fsolve[0], sol_fsolve[1], 'ko', label='Solución')

plt.title('Inciso b)')
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend()
plt.grid()
plt.show()
```

---

## Ejercicio 2

Aproxima la solución de los siguientes sistemas no lineales.

**(a)**

\begin{eqnarray}
15x_1 + x_2^2 - 4x_3 &=& 13, \\
x_1^2 + 10x_2 - x_3 &=& 11, \\
x_2^3 - 25x_3 &=& -22.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]
    x3 = X[2]

    f1 = 15*x1 + x2**2 - 4*x3 - 13
    f2 = x1**2 + 10*x2 - x3 - 11
    f3 = x2**3 - 25*x3 + 22

    return [f1, f2, f3]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [1, 1, 1])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2 + f[2]**2

sol_min = minimize(objetivo, [1, 1, 1])
print("Solución con minimize:", sol_min.x)
```

**(b)**

\begin{eqnarray}
10x_1 - 2x_2^2 + x_2 - 2x_3 - 5 &=& 0, \\
8x_2^2 + 4x_3^2 - 9 &=& 0, \\
8x_2 x_3 + 4 &=& 0.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]
    x3 = X[2]

    
    f1 = 10*x1 - 2*x2**2 + x2 - 2*x3 - 5
    f2 = 8*x2**2 + 4*x3**2 - 9
    f3 = 8*x2*x3 + 4

    return [f1, f2, f3]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [1, 1, -1])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2 + f[2]**2

sol_min = minimize(objetivo, [1, 1, -1])
print("Solución con minimize:", sol_min.x)
```


**(c)**

\begin{eqnarray}
x_1^3 + x_1^2 x_2 - x_1 x_3 + 6 &=& 0, \\
e^{x_1} + e^{x_2} - x_3 &=& 0, \\
x_2^2 - 2x_1 x_3 &=& 4.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]
    x3 = X[2]

    
    f1 = x1**3 + x1**2*x2 - x1*x3 + 6
    f2 = np.exp(x1) + np.exp(x2) - x3
    f3 = x2**2 - 2*x1*x3 - 4

    return [f1, f2, f3]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [-1, 1, 4])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2 + f[2]**2

sol_min = minimize(objetivo, [-1, 1, 4])
print("Solución con minimize:", sol_min.x)
```

**(d)**

\begin{eqnarray}
x_1 + \cos(x_1 x_2 x_3) - 1 &=& 0, \\
(1 - x_1)^{1/4} + x_2 + 0.05x_3^2 - 0.15x_3 - 1 &=& 0, \\
-x_1^2 - 0.1x_2^2 + 0.01x_2 + x_3 - 1 &=& 0.
\end{eqnarray}

```{python}
def sistema(X):
    x1 = X[0]
    x2 = X[1]
    x3 = X[2]

    
    f1 = x1 + np.cos(x1*x2*x3) - 1
    f2 = (1 - x1)**(1/4) + x2 + 0.05*x3**2 - 0.15*x3 - 1
    f3 = -x1**2 - 0.1*x2**2 + 0.01*x2 + x3 - 1

    return [f1, f2, f3]
```

**Con fsolve**

```{python}
sol_fsolve = fsolve(sistema, [0,0, 1])
print("Solución con fsolve:", sol_fsolve)
```

**Con minimize**

```{python}
def objetivo(X):
    f = sistema(X)
    return f[0]**2 + f[1]**2 + f[2]**2

sol_min = minimize(objetivo, [0, 0, 1])
print("Solución con minimize:", sol_min.x)
```

---

## Ejercicio 3

Aproxima los mínimos de las siguientes funciones.

**(a)** Grafica la superficie $z = g(x_1, x_2)$ indicando el mínimo encontrado.

\begin{equation}
g(x_1, x_2) = \cos(x_1 + x_2) + \sin x_1 + \cos x_2.
\end{equation}

```{python}
def g(X):
    x1 = X[0]
    x2 = X[1]

    return np.cos(x1 + x2) + np.sin(x1) + np.cos(x2)
```

**Con minimize**

```{python}
sol_min = minimize(g, [0, 0])
print("Mínimo en:", sol_min.x)
print("Valor mínimo:", sol_min.fun)
```

**Gráfica**

```{python}
x1 = np.linspace(-6, 6, 300)
x2 = np.linspace(-6, 6, 300)

X1, X2 = np.meshgrid(x1, x2)

Z = np.cos(X1 + X2) + np.sin(X1) + np.cos(X2)

fig = plt.figure(figsize=(9,6))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X1, X2, Z, alpha=0.8)

ax.scatter(sol_min.x[0], sol_min.x[1], sol_min.fun,
           color='blue', s=50, label='Mínimo')

ax.set_title('Superficie de g(x1, x2)')
ax.set_xlabel('x1')
ax.set_ylabel('x2')
ax.set_zlabel('g(x1, x2)')

plt.legend()
plt.show()
```

**(b)** Grafica la superficie $z = g(x_1, x_2)$ indicando el mínimo encontrado.

\begin{equation}
g(x_1, x_2) = 100(x_1^2 - x_2)^2 + (1 - x_1)^2.
\end{equation}

```{python}
def g(X):
    x1 = X[0]
    x2 = X[1]

    return 100*(x1**2 - x2)**2 + (1 - x1)**2
```

**Con minimize**

```{python}
sol_min = minimize(g, [0, 0])

print("Mínimo en:", sol_min.x)
print("Valor mínimo:", sol_min.fun)
```

**Gráfica**

```{python}
x1 = np.linspace(-2, 2, 300)
x2 = np.linspace(-1, 3, 300)

X1, X2 = np.meshgrid(x1, x2)

Z = 100*(X1**2 - X2)**2 + (1 - X1)**2

fig = plt.figure(figsize=(9,6))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X1, X2, Z, alpha=0.8)

ax.scatter(sol_min.x[0],
           sol_min.x[1],
           sol_min.fun,
           color='pink',
           s=50,
           label='Mínimo')

ax.set_title('Función de Rosenbrock')
ax.set_xlabel('x1')
ax.set_ylabel('x2')
ax.set_zlabel('g(x1,x2)')

plt.legend()
plt.show()
```

**(c)**

\begin{equation}
g(x_1, x_2, x_3) = x_1^2 + 2x_2^2 + x_3^2 - 2x_1 x_2 + 2x_1 - 2.5x_2 - x_3 + 2.
\end{equation}

```{python}
def g(X):
    x1 = X[0]
    x2 = X[1]
    x3 = X[2]

    return x1**2 + 2*x2**2 + x3**2 - 2*x1*x2 + 2*x1 - 2.5*x2 - x3 + 2
```

**Con minimize**

```{python}
sol_min = minimize(g, [0, 0, 0])

print("Mínimo en:", sol_min.x)
print("Valor mínimo:", sol_min.fun)
```

**Gráfica**

```{python}
x1 = np.linspace(-2, 2, 100)
x2 = np.linspace(-1, 2, 100)

X1, X2 = np.meshgrid(x1, x2)

x3 = 0.5

Z = X1**2 + 2*X2**2 + x3**2 - 2*X1*X2 + 2*X1 - 2.5*X2 - x3 + 2

fig = plt.figure(figsize=(9,6))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X1, X2, Z, alpha=0.8)

ax.scatter(-0.75, 0.5, 0.125,
           color='red',
           s=50,
           label='Mínimo')

ax.set_title('Función g con x3 = 0.5')
ax.set_xlabel('x1')
ax.set_ylabel('x2')
ax.set_zlabel('g')

plt.legend()
plt.show()
```

**(d)**

\begin{equation}
g(x_1, x_2, x_3) = x_1^4 + 2x_2^4 + 3x_3^4 + 1.01.
\end{equation}

```{python}
def g(X):
    x1 = X[0]
    x2 = X[1]
    x3 = X[2]

    return x1**4 + 2*x2**4 + 3*x3**4 + 1.01

```

**Con minimize**

```{python}
sol_min = minimize(g, [1, 1, 1])

print("Mínimo en:", sol_min.x)
print("Valor mínimo:", sol_min.fun)
```

**Gráfica**

```{python}
x1 = np.linspace(-2, 2, 100)
x2 = np.linspace(-2, 2, 100)

X1, X2 = np.meshgrid(x1, x2)

x3 = 0

Z = X1**4 + 2*X2**4 + 3*x3**4 + 1.01

fig = plt.figure(figsize=(9,6))
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(X1, X2, Z, alpha=0.8)

ax.scatter(0, 0, 1.01,
           color='yellow',
           s=50,
           label='Mínimo')

ax.set_title('Función g con x3 = 0')
ax.set_xlabel('x1')
ax.set_ylabel('x2')
ax.set_zlabel('g')

plt.legend()
plt.show()
```